### PR TITLE
II-12971 Adding collectd project that does get successfully deployed.

### PR DESCRIPTION
**Pull request by yashgiri**
- Removing reporting_config.json from gitignore as it is preventing successful deploy

### CODE REVIEW

**Review by haofu-if — CHANGES_REQUESTED** [review]
Cannot remove reporting_config.json from .gitignore, this file includes timestamp of the running status. If should automatically created by the main py fiile

**Comment by yashgiri** [comment]
@haofu-if Is there any code-example which already generates reporting_config.json. 
The reporting_config.json has the following values. 
```
{"keep_file_days": "5", "prev_endtime": "20220315191023", "reporting_interval": "1", "delta_fields": ["CPU", "DiskRead", "DiskWrite", "NetworkIn", "NetworkOut", "InOctets", "OutOctets", "InErrors", "OutErrors", "InDiscards", "OutDiscards"]}
```
how should i populate the data for such a file if the file does not exist ?

**Comment by yashgiri** [comment]
I have updated the PR please let me know what other changes might be needed ?

**Comment by yashgiri** [comment]
I have confirmed with Joyce keeping the file in gitignore and getting it uploaded is fine for now.

**Comment by yashgiri** [comment]
Pr updated with reporting_config.json file removed and gitignore file fixed as you have suggested.
Added the code logic to create the file in the main python program.

**Review by haofu-if — APPROVED** [review]

**Pull request merged**
